version: "3.3"
services:
  website:
    build: ./Frontend/website
    ports:
      - 3000:3000
    expose:
      - "3000"
    env_file:
      - ./Frontend/website/.env
  re-admin:
    build: ./Frontend/re-admin
    ports:
      - 3001:3001
    expose:
      - "3001"

